name: UltraDupe
version: '${version}'
main: io.github.thetrouper.ultradupe.UltraDupe
api-version: 1.19
authors: [ TheTrouper ]
description: Detect Block and Ban players who attempt to grief your server.
website: https://thetrouper.github.io/
softdepend: [ ProtocolLib ]
permissions:
  ultradupe.dupe:
    description: Access to the dupe
    default: op
  ultradupe.dupebans.edit:
    description: edit the dupe ban list
    default: op
  ultradupe.dupebans:
    description: see the dupe ban list
    default: op

commands:
  ultradupe:
    description: A command for testing.
    usage: /ultradupe
    permission: ultradupe.info
    permission-message: You do not have permission!
    aliases:
      - dupe
      - d
      - ud
  multiply:
    description: A command for testing.
    usage: /ultradupe
    permission: ultradupe.info
    permission-message: You do not have permission!
    aliases:
      - mult
      - m
      - um
  dupebans:
    description: dupe bans
    usage: /dupebans [add|remove]
    permission: ultradupe.dupebans