name: UltraDupe
version: '${version}'
main: me.trouper.ultradupe.UltraDupe
api-version: 1.19
authors: [ TheTrouper ]
description: The only acceptable dupe plugin.
website: https://thetrouper.github.io/
permissions:
  ultradupe.multiply:
    default: op
    description: Access to the multiply/exponential dupe feature
  ultradupe.dupe:
    default: op
    description: Access to the dupe feature
  ultradupe.bypass.mult-cooldown:
    default: op
    description: Bypass the multiply cooldown
  ultradupe.bypass.dupe-cooldown:
    default: op
    description: Bypass the dupe cooldown
  ultradupe.bypass.bans:
    default: op
    description: Bypass all the dupe bans
  ultradupe.dupebans:
    default: op
    description: see the dupe ban list
  ultradupe.dupebans.edit:
    default: op
    description: edit the dupe ban list

commands:
  ultradupe:
    description: Admin command to edit and bypass dupebans
    usage: /ultradupe
    permission: ultradupe.admin
    aliases:
      - ud
  duplicate:
    description: A command for testing.
    usage: /dupe [int]
    permission: ultradupe.dupe
    permission-message: You do not have permission!
    aliases:
      - dupe
      - d
  multiply:
    description: A command for testing.
    usage: /multiply [int]
    permission: ultradupe.multiply
    permission-message: You do not have permission!
    aliases:
      - mult
      - m
  dupebans:
    description: dupe bans
    usage: /dupebans
    permission: ultradupe.dupebans